export function createWhatsAppText({ farm = {}, prediction = {}, mandi = {}, revenueGain = 0, productCost = 0 }) {
  return [`AgroVani farm update`, `${farm.name || 'Farmer'} • ${farm.cropType || prediction.crop || 'Crop'} • ${farm.village || farm.district || 'India'}`, `Predicted yield: ${prediction.lowerBound ?? '—'}–${prediction.upperBound ?? '—'} ${prediction.unit || 'quintal/acre'}`, `Estimated treatment advantage: ${prediction.estimatedTreatmentAdvantage ?? '—'} quintal/acre`, `Estimated revenue gain: ₹${Number(revenueGain).toLocaleString('en-IN')} | Product cost: ₹${Number(productCost).toLocaleString('en-IN')}`, `Mandi: ${mandi.modalPrice ? `₹${mandi.modalPrice}/${mandi.unit || 'quintal'}` : 'insufficient data'}`, `Model estimate, not causal proof or financial advice. Source time: ${prediction.dataFreshness || '—'}`].join('\n')
}

export function createReport({ farm = {}, prediction = {}, mandi = {}, revenueGain = 0, productCost = 0 }) {
  const netProfit = Number(revenueGain) - Number(productCost)
  return { farm, prediction, mandi, revenueGain: Number(revenueGain), productCost: Number(productCost), netProfit, assumptions: ['Baseline observational model; no causal claim.', 'Revenue uses the supplied mandi modal price and farm area.', 'Missing or stale market data is shown as insufficient data.'], generatedAt: new Date().toISOString() }
}

export function reportHtml(report) {
  const { farm, prediction, mandi } = report
  return `<!doctype html><html><head><meta charset="utf-8"><title>AgroVani farmer report</title><style>body{font:14px Arial,sans-serif;color:#17221d;max-width:760px;margin:32px auto;padding:0 20px}h1{color:#006a42}section{border-top:1px solid #cbd5d1;padding:12px 0}dt{font-weight:bold;float:left;clear:left;width:220px}dd{margin-left:230px;margin-bottom:6px}@media print{body{margin:12mm}}</style></head><body><h1>AgroVani farmer report</h1><p>${farm.name || 'Farmer'} · ${farm.cropType || prediction.crop || 'Crop'} · ${farm.village || farm.district || 'India'}</p><section><h2>Yield estimate</h2><dl><dt>Predicted range</dt><dd>${prediction.lowerBound ?? '—'}–${prediction.upperBound ?? '—'} ${prediction.unit || 'quintal/acre'}</dd><dt>Estimated treatment advantage</dt><dd>${prediction.estimatedTreatmentAdvantage ?? '—'} quintal/acre</dd><dt>Risk level</dt><dd>${prediction.riskLevel || '—'} · confidence ${prediction.confidenceScore ?? '—'}</dd></dl></section><section><h2>Money view</h2><dl><dt>Estimated revenue gain</dt><dd>₹${report.revenueGain.toLocaleString('en-IN')}</dd><dt>Product cost</dt><dd>₹${report.productCost.toLocaleString('en-IN')}</dd><dt>Net profit estimate</dt><dd>₹${report.netProfit.toLocaleString('en-IN')}</dd><dt>MSP / mandi</dt><dd>${mandi.msp ? `₹${mandi.msp} / ₹${mandi.modalPrice}` : 'insufficient data'}</dd></dl></section><section><h2>Assumptions and source</h2><p>${report.assumptions.join(' ')}</p><p>Data source timestamp: ${prediction.dataFreshness || report.generatedAt}</p></section><p><strong>Disclaimer:</strong> Explanations are model-based, not causal attribution. Market signals are not financial advice.</p><script>window.onload=()=>window.print()</script></body></html>`
}